api pytest:
    image: alpine@sha256:4edbd2beb5f78b1014028f4fbb99f3237d9561100b6881aabbf5acce2c4f9454
    services:
        - name: mooseagency/postgresql:14.7-1@sha256:907984140556c7368c5245017aaeab1a045050062bebddd05204805292c31b2b
          alias: postgresql
          command:
              - postgres
              - -cfsync=off
              - -cfull_page_writes=off
              - -cautovacuum=off
    variables:
        POSTGRESQL_INITDB_DATABASES: "admin:secret@default"
    script:
        - echo "Renovate test"
