api pytest:
    image: alpine@sha256:d6d0a0eb4d40ef96f2310ead734848b9c819bb97c9d846385c4aca1767186cd4
    services:
        - name: mooseagency/postgresql:12.3-1@sha256:a5a65569456f221ee1f8a0b3b4e2d440eb5830772d9440c9b30b1dbfd454c778
          alias: postgresql
          command:
              - postgres@sha256:d1db54eade17ebfaa6cfdca90c83f8cb0d54bcceb1270a0848e0b216d50c325c
              - -cfsync=off
              - -cfull_page_writes=off
              - -cautovacuum=off
    variables:
        POSTGRESQL_INITDB_DATABASES: "admin:secret@default"
    script:
        - echo "Renovate test"
